apiVersion: v1
kind: Secret
metadata:
  name: elastic-cloud-secret
type: Opaque
stringData:
  elastic.cloud.id: <SPECIFY_ELASTIC_CLOUD_ID>
  elastic.cloud.auth: <SPECIFY_ELASTIC_CLOUD_AUTH_IN_FORMAT_OF_USERNAME:PASSWORD>
# You can use data section instead, which requires values base64 encoded,  
# see sample shell commands below on how to generate them:
# $ echo "base64 encoded elastic.cloud.id is:  $(echo -n ${cloudId} | base64)"
# $ echo "base64 encoded elastic.cloud.auth is:  $(echo -n ${username}:${password} | base64)"
#data:
  #elastic.cloud.id: <SPECIFY_BASE64_ENCODED_ELASTIC_CLOUD_ID>
  #elastic.cloud.auth: <SPECIFY_BASE64_ENCODED_ELASTIC_CLOUD_AUTH_IN_FORMAT_OF_USERNAME:PASSWORD>