apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: elk-integration-demo
spec:
  replicas: 1
  applicationImage: 'docker.io/majguo/elk-integration:1.0'
  expose: true
  volumeMounts:
  - name: logs-volume
    mountPath: /logs
  volumes:
  - name: logs-volume
    emptyDir: {}
  - name: config
    configMap:
      defaultMode: 0600
      name: filebeat-config
  sidecarContainers:
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:7.6.2
    args: [
      "-c", "/etc/filebeat.yml",
      "-e",
    ]
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    env:
    - name: ELASTIC_CLOUD_ID
      valueFrom:
        secretKeyRef:
          name: elastic-cloud-secret
          key: elastic.cloud.id
    - name: ELASTIC_CLOUD_AUTH
      valueFrom:
        secretKeyRef:
          name: elastic-cloud-secret
          key: elastic.cloud.auth
    volumeMounts:
    - name: config
      mountPath: /etc/filebeat.yml
      readOnly: true
      subPath: filebeat.yml
    - name: logs-volume
      mountPath: /logs
      readOnly: true
